title: Reagan's GitHub Page
author: Reagan Becnel
email: reb8510@utulsa.edu
theme: minima 
description: > # this means to ignore newlines until "baseurl:"
  On this GitHub page, you will find all you need to know about me and my journey through Programming 1!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
